/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const pause_app: () => void;
export const restart_app: () => void;
export const resume_app: () => void;
export const main: (a: number, b: number) => number;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___js_sys_5214f86215394925___Array__web_sys_48c635298d0a325a___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_fb1a4a267c58a04b___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___core_ed718c3d60ebd546___option__Option_web_sys_48c635298d0a325a___features__gen_Blob__Blob_______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__13: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__14: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__15: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__16: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__17: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__18: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke___wasm_bindgen_fb1a4a267c58a04b___JsValue______true__1__19: (a: number, b: number, c: any) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_fb1a4a267c58a04b___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
